### ISSUE TITLE
Unable to create new wallet

### ISSUE THREAD

**Issue by varnav** [XMRto/monero#4]
I'm trying to create a new wallet:

`docker run --rm -it -v /opt/monero:/monero xmrto/monero monero-wallet-cli --generate-new-wallet wallet`

But it fails with `Error: failed to generate new wallet: failed to save file "wallet.keys"` after I select English.

**Comment by normoes** [comment]
Hi,
Sorry for replying this late.

The cause for this is most likely because of permissions and your user ID.

The message `Error: failed to generate new wallet: failed to save file "wallet.keys"` points into this direction.

The default user ID used in the container is `1000`. So in case the directory you mount into your container (`opt/monero`) is not allowed to be written to by user id `1000`, the file cannot be written.

You can try to check permissions of the directory `ls -l /opt/monero` (or `ls -n`) and run the container as another user by adding the optionn `-e USER_ID=</opt/monero/user_id>`.

Example: 
```
docker run --rm -it -e USER_ID=500 -v /opt/monero:/monero xmrto/monero monero-wallet-cli --generate-new-wallet wallet
```

**Comment by normoes** [comment]
@varnav 

Did you have the chance to try again?

**Comment by varnav** [comment]
Yes, I remounted it as volume. Not sure if it's monero's bug or my fault. Thanks!
